### PR TITLE
Fixes issue where a deleted AAP Job causes terraform plan to fail

### LINKED ISSUE #59: Terraform Plan Fails After AAP Job Cleanup
Terraform Provider Version: ansible/terraform-provider-aap v1.1.2
Terraform version: 1.11.3

Problem Description:

Terraform's aap_job resource allows launching Ansible Automation Platform (AAP) jobs. If Terraform performs a new plan after an existing AAP job has been deleted by AAP's scheduled "Cleanup Job Schedule" (a built-in management job), the Terraform plan fails with a 404 error.

The error received is:

```
Error: Unexpected HTTP status code received for GET request to path https://<aap>/api/controller/v2/jobs/85/ with aap_job.vm_demo_job
on main.tf line 52, in resource "aap_job" "vm_demo_job":
resource "aap_job" "vm_demo_job" {
Expected one of ([200]), got (404). Response details: map [detail:No Job matches the given query.]
```

Steps to Reproduce:

Use Terraform to create an aap_job resource.

Let the job complete.

Allow the AAP Cleanup Job Schedule (automatically generated management job) to remove the completed job.

Run terraform plan again.

Expected Behavior:
Terraform gracefully handles missing previous jobs by recognising the job no longer exists and plans to create a new job if required.

Actual Behavior:
Terraform fails during the planning phase due to the missing job, resulting in a 404 error.

Potential Root Cause:
The provider attempts to fetch the job state without handling scenarios where the job has been deleted by AAP management schedules. The provider should handle 404 responses gracefully.

Suggested Resolution:
Modify the provider logic to:

Detect a 404 status on job fetch.

Consider the job as non-existent and plan accordingly (e.g., show a forced new resource or clean state).

Terraform Configuration Snippet:

```
resource "aap_job" "vm_demo_job" {
  job_template_id = var.job_template_id
  inventory_id    = aap_inventory.vm_inventory.id
}
```

Environment:
AAP version: 2.5
Additional Context:
The AAP built-in scheduled job is named: "Cleanup Job Schedule" (Management job).

### PR DESCRIPTION
**Pull request by dleehr**
Updates the behavior for the `aap_job` resource to handle a 404 error in the `Read` method. A 404 error indicates the job recorded in terraform state was created by the provider but has since been deleted from AAP. As noted in #59, this scenario is common because AAP cleans up old jobs by default and results in plan failures that require manual state modification.

With this change, we remove the resource from the state if a 404 is encountered, so that the plan marks it as disappeared and plans to re-create. On apply, it is re-created. I've verified the acceptance tests locally against AAP 2.5.

This PR also updates the regex patterns in the acceptance tests to support AAP 2.5 and configured `main.go` to support debugging with a `-debug` flag.

Fixes #59

### CODE REVIEW

**Comment by dleehr** [comment]
Looks like I need a changelog fragment for this

**Comment by dleehr** [comment]
<details>

<summary>Local acceptance test output (click to expand)</summary>

```
$ git rev-parse HEAD
b92bd085d03c28b3173cf4da46f5c3467eefa48a

$ TF_ACC=1 AAP_HOST="http://localhost:9080" go test -count=1 -v ./...
?   	github.com/ansible/terraform-provider-aap	[no test files]
=== RUN   TestComputeURLPath
=== RUN   TestComputeURLPath/case_1
=== RUN   TestComputeURLPath/case_2
=== RUN   TestComputeURLPath/case_3
=== RUN   TestComputeURLPath/case_4
--- PASS: TestComputeURLPath (0.00s)
    --- PASS: TestComputeURLPath/case_1 (0.00s)
    --- PASS: TestComputeURLPath/case_2 (0.00s)
    --- PASS: TestComputeURLPath/case_3 (0.00s)
    --- PASS: TestComputeURLPath/case_4 (0.00s)
=== RUN   TestReadApiEndpoint
=== RUN   TestReadApiEndpoint/AAP_2.4
=== RUN   TestReadApiEndpoint/AAP_2.5+
--- PASS: TestReadApiEndpoint (0.00s)
    --- PASS: TestReadApiEndpoint/AAP_2.4 (0.00s)
    --- PASS: TestReadApiEndpoint/AAP_2.5+ (0.00s)
=== RUN   TestGroupResourceSchema
=== PAUSE TestGroupResourceSchema
=== RUN   TestGroupResourceCreateRequestBody
=== RUN   TestGroupResourceCreateRequestBody/test_with_unknown_values
=== RUN   TestGroupResourceCreateRequestBody/test_with_null_values
=== RUN   TestGroupResourceCreateRequestBody/test_with_some_values
=== RUN   TestGroupResourceCreateRequestBody/test_with_all_values
--- PASS: TestGroupResourceCreateRequestBody (0.00s)
    --- PASS: TestGroupResourceCreateRequestBody/test_with_unknown_values (0.00s)
    --- PASS: TestGroupResourceCreateRequestBody/test_with_null_values (0.00s)
    --- PASS: TestGroupResourceCreateRequestBody/test_with_some_values (0.00s)
    --- PASS: TestGroupResourceCreateRequestBody/test_with_all_values (0.00s)
=== RUN   TestGroupResourceParseHttpResponse
=== RUN   TestGroupResourceParseHttpResponse/test_with_JSON_error
=== RUN   TestGroupResourceParseHttpResponse/test_with_missing_values
=== RUN   TestGroupResourceParseHttpResponse/test_with_all_values
--- PASS: TestGroupResourceParseHttpResponse (0.00s)
    --- PASS: TestGroupResourceParseHttpResponse/test_with_JSON_error (0.00s)
    --- PASS: TestGroupResourceParseHttpResponse/test_with_missing_values (0.00s)
    --- PASS: TestGroupResourceParseHttpResponse/test_with_all_values (0.00s)
=== RUN   TestAccGroupResource
--- PASS: TestAccGroupResource (5.60s)
=== RUN   TestSliceDifference
--- PASS: TestSliceDifference (0.00s)
=== RUN   TestExtractIDs
--- PASS: TestExtractIDs (0.00s)
=== RUN   TestHostResourceSchema
=== PAUSE TestHostResourceSchema
=== RUN   TestHostResourceCreateRequestBody
=== RUN   TestHostResourceCreateRequestBody/test_with_unknown_values
=== RUN   TestHostResourceCreateRequestBody/test_with_null_values
=== RUN   TestHostResourceCreateRequestBody/test_with_some_values
=== RUN   TestHostResourceCreateRequestBody/test_with_all_values
--- PASS: TestHostResourceCreateRequestBody (0.00s)
    --- PASS: TestHostResourceCreateRequestBody/test_with_unknown_values (0.00s)
    --- PASS: TestHostResourceCreateRequestBody/test_with_null_values (0.00s)
    --- PASS: TestHostResourceCreateRequestBody/test_with_some_values (0.00s)
    --- PASS: TestHostResourceCreateRequestBody/test_with_all_values (0.00s)
=== RUN   TestHostResourceParseHttpResponse
=== RUN   TestHostResourceParseHttpResponse/test_with_JSON_error
=== RUN   TestHostResourceParseHttpResponse/test_with_missing_values
=== RUN   TestHostResourceParseHttpResponse/test_with_all_values
--- PASS: TestHostResourceParseHttpResponse (0.00s)
    --- PASS: TestHostResourceParseHttpResponse/test_with_JSON_error (0.00s)
    --- PASS: TestHostResourceParseHttpResponse/test_with_missing_values (0.00s)
    --- PASS: TestHostResourceParseHttpResponse/test_with_all_values (0.00s)
=== RUN   TestAccHostResource
--- PASS: TestAccHostResource (6.04s)
=== RUN   TestInventoryDataSourceSchema
=== PAUSE TestInventoryDataSourceSchema
=== RUN   TestInventoryDataSourceParseHttpResponse
=== RUN   TestInventoryDataSourceParseHttpResponse/JSON_error
=== RUN   TestInventoryDataSourceParseHttpResponse/missing_values
=== RUN   TestInventoryDataSourceParseHttpResponse/all_values
--- PASS: TestInventoryDataSourceParseHttpResponse (0.00s)
    --- PASS: TestInventoryDataSourceParseHttpResponse/JSON_error (0.00s)
    --- PASS: TestInventoryDataSourceParseHttpResponse/missing_values (0.00s)
    --- PASS: TestInventoryDataSourceParseHttpResponse/all_values (0.00s)
=== RUN   TestAccInventoryDataSource
--- PASS: TestAccInventoryDataSource (2.17s)
=== RUN   TestInventoryResourceSchema
=== PAUSE TestInventoryResourceSchema
=== RUN   TestInventoryResourceGenerateRequestBody
=== RUN   TestInventoryResourceGenerateRequestBody/unknown_values
=== RUN   TestInventoryResourceGenerateRequestBody/null_values
=== RUN   TestInventoryResourceGenerateRequestBody/provided_values
--- PASS: TestInventoryResourceGenerateRequestBody (0.00s)
    --- PASS: TestInventoryResourceGenerateRequestBody/unknown_values (0.00s)
    --- PASS: TestInventoryResourceGenerateRequestBody/null_values (0.00s)
    --- PASS: TestInventoryResourceGenerateRequestBody/provided_values (0.00s)
=== RUN   TestInventoryResourceParseHttpResponse
=== RUN   TestInventoryResourceParseHttpResponse/JSON_error
=== RUN   TestInventoryResourceParseHttpResponse/missing_values
=== RUN   TestInventoryResourceParseHttpResponse/all_values
--- PASS: TestInventoryResourceParseHttpResponse (0.00s)
    --- PASS: TestInventoryResourceParseHttpResponse/JSON_error (0.00s)
    --- PASS: TestInventoryResourceParseHttpResponse/missing_values (0.00s)
    --- PASS: TestInventoryResourceParseHttpResponse/all_values (0.00s)
=== RUN   TestAccInventoryResource
--- PASS: TestAccInventoryResource (4.32s)
=== RUN   TestJobResourceSchema
=== PAUSE TestJobResourceSchema
=== RUN   TestJobResourceCreateRequestBody
=== RUN   TestJobResourceCreateRequestBody/unknown_values
=== RUN   TestJobResourceCreateRequestBody/null_values
=== RUN   TestJobResourceCreateRequestBody/extra_vars_only
=== RUN   TestJobResourceCreateRequestBody/inventory_vars_only
=== RUN   TestJobResourceCreateRequestBody/combined
=== RUN   TestJobResourceCreateRequestBody/manual_triggers
--- PASS: TestJobResourceCreateRequestBody (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/unknown_values (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/null_values (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/extra_vars_only (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/inventory_vars_only (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/combined (0.00s)
    --- PASS: TestJobResourceCreateRequestBody/manual_triggers (0.00s)
=== RUN   TestJobResourceParseHttpResponse
=== RUN   TestJobResourceParseHttpResponse/JSON_error
=== RUN   TestJobResourceParseHttpResponse/no_ignored_fields
=== RUN   TestJobResourceParseHttpResponse/ignored_fields
--- PASS: TestJobResourceParseHttpResponse (0.00s)
    --- PASS: TestJobResourceParseHttpResponse/JSON_error (0.00s)
    --- PASS: TestJobResourceParseHttpResponse/no_ignored_fields (0.00s)
    --- PASS: TestJobResourceParseHttpResponse/ignored_fields (0.00s)
=== RUN   TestAccAAPJob_basic
--- PASS: TestAccAAPJob_basic (2.19s)
=== RUN   TestAccAAPJob_UpdateWithSameParameters
--- PASS: TestAccAAPJob_UpdateWithSameParameters (3.05s)
=== RUN   TestAccAAPJob_UpdateWithNewInventoryId
--- PASS: TestAccAAPJob_UpdateWithNewInventoryId (42.01s)
=== RUN   TestAccAAPJob_UpdateWithTrigger
--- PASS: TestAccAAPJob_UpdateWithTrigger (3.21s)
=== RUN   TestAccAAPJob_disappears
--- PASS: TestAccAAPJob_disappears (44.08s)
=== RUN   TestReadValues
=== RUN   TestReadValues/No_defined_values
=== RUN   TestReadValues/Using_env_variables_only
=== RUN   TestReadValues/Using_both_configuration_and_envs_value
=== RUN   TestReadValues/Using_configuration_value
=== RUN   TestReadValues/Bad_value_for_env_variable
=== RUN   TestReadValues/Using_null_values_in_configuration
--- PASS: TestReadValues (0.00s)
    --- PASS: TestReadValues/No_defined_values (0.00s)
    --- PASS: TestReadValues/Using_env_variables_only (0.00s)
    --- PASS: TestReadValues/Using_both_configuration_and_envs_value (0.00s)
    --- PASS: TestReadValues/Using_configuration_value (0.00s)
    --- PASS: TestReadValues/Bad_value_for_env_variable (0.00s)
    --- PASS: TestReadValues/Using_null_values_in_configuration (0.00s)
=== RUN   TestGetURL
=== RUN   TestGetURL/https://example.com
=== RUN   TestGetURL/https://example.com/
=== RUN   TestGetURL/https://example.com#01
=== RUN   TestGetURL/invalid-url
--- PASS: TestGetURL (0.00s)
    --- PASS: TestGetURL/https://example.com (0.00s)
    --- PASS: TestGetURL/https://example.com/ (0.00s)
    --- PASS: TestGetURL/https://example.com#01 (0.00s)
    --- PASS: TestGetURL/invalid-url (0.00s)
=== RUN   TestParseStringValue
=== RUN   TestParseStringValue/Test_non-empty_string
=== RUN   TestParseStringValue/Test_empty_string
--- PASS: TestParseStringValue (0.00s)
    --- PASS: TestParseStringValue/Test_non-empty_string (0.00s)
    --- PASS: TestParseStringValue/Test_empty_string (0.00s)
=== RUN   TestParseNormalizedValue
=== RUN   TestParseNormalizedValue/Test_non-empty_string
=== RUN   TestParseNormalizedValue/Test_empty_string
--- PASS: TestParseNormalizedValue (0.00s)
    --- PASS: TestParseNormalizedValue/Test_non-empty_string (0.00s)
    --- PASS: TestParseNormalizedValue/Test_empty_string (0.00s)
=== CONT  TestGroupResourceSchema
=== CONT  TestInventoryResourceSchema
=== CONT  TestInventoryDataSourceSchema
=== CONT  TestJobResourceSchema
=== CONT  TestHostResourceSchema
--- PASS: TestInventoryResourceSchema (0.00s)
--- PASS: TestGroupResourceSchema (0.00s)
--- PASS: TestInventoryDataSourceSchema (0.00s)
--- PASS: TestJobResourceSchema (0.00s)
--- PASS: TestHostResourceSchema (0.00s)
PASS
ok  	github.com/ansible/terraform-provider-aap/internal/provider	113.012s
=== RUN   TestAAPCustomStringTypeValidate
=== PAUSE TestAAPCustomStringTypeValidate
=== RUN   TestAAPCustomStringTypeValueFromTerraform
=== PAUSE TestAAPCustomStringTypeValueFromTerraform
=== RUN   TestAAPCustomStringStringSemanticEquals
=== PAUSE TestAAPCustomStringStringSemanticEquals
=== CONT  TestAAPCustomStringTypeValidate
=== RUN   TestAAPCustomStringTypeValidate/yaml_string_no_newline
=== CONT  TestAAPCustomStringStringSemanticEquals
=== RUN   TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_values
=== PAUSE TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_values
=== RUN   TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_names
=== PAUSE TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_names
=== PAUSE TestAAPCustomStringTypeValidate/yaml_string_no_newline
=== CONT  TestAAPCustomStringTypeValueFromTerraform
=== RUN   TestAAPCustomStringTypeValidate/wrong-value-type
=== RUN   TestAAPCustomStringTypeValueFromTerraform/true
=== PAUSE TestAAPCustomStringTypeValueFromTerraform/true
=== PAUSE TestAAPCustomStringTypeValidate/wrong-value-type
=== RUN   TestAAPCustomStringTypeValueFromTerraform/unknown
=== RUN   TestAAPCustomStringTypeValidate/empty-struct
=== PAUSE TestAAPCustomStringTypeValueFromTerraform/unknown
=== PAUSE TestAAPCustomStringTypeValidate/empty-struct
=== RUN   TestAAPCustomStringTypeValueFromTerraform/null
=== RUN   TestAAPCustomStringTypeValidate/null
=== PAUSE TestAAPCustomStringTypeValueFromTerraform/null
=== RUN   TestAAPCustomStringTypeValueFromTerraform/wrongType
=== PAUSE TestAAPCustomStringTypeValidate/null
=== PAUSE TestAAPCustomStringTypeValueFromTerraform/wrongType
=== RUN   TestAAPCustomStringTypeValidate/unknown
=== CONT  TestAAPCustomStringTypeValueFromTerraform/wrongType
=== RUN   TestAAPCustomStringStringSemanticEquals/not_equal_-_additional_field
=== PAUSE TestAAPCustomStringStringSemanticEquals/not_equal_-_additional_field
=== RUN   TestAAPCustomStringStringSemanticEquals/not_equal_-_array_item_order_difference
=== PAUSE TestAAPCustomStringStringSemanticEquals/not_equal_-_array_item_order_difference
=== RUN   TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_byte-for-byte_match
=== PAUSE TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_byte-for-byte_match
=== CONT  TestAAPCustomStringTypeValueFromTerraform/true
=== PAUSE TestAAPCustomStringTypeValidate/unknown
=== CONT  TestAAPCustomStringTypeValueFromTerraform/null
=== CONT  TestAAPCustomStringTypeValueFromTerraform/unknown
--- PASS: TestAAPCustomStringTypeValueFromTerraform (0.00s)
    --- PASS: TestAAPCustomStringTypeValueFromTerraform/wrongType (0.00s)
    --- PASS: TestAAPCustomStringTypeValueFromTerraform/true (0.00s)
    --- PASS: TestAAPCustomStringTypeValueFromTerraform/null (0.00s)
    --- PASS: TestAAPCustomStringTypeValueFromTerraform/unknown (0.00s)
=== RUN   TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_whitespace_difference
=== RUN   TestAAPCustomStringTypeValidate/json_object
=== PAUSE TestAAPCustomStringTypeValidate/json_object
=== RUN   TestAAPCustomStringTypeValidate/json_string
=== PAUSE TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_whitespace_difference
=== PAUSE TestAAPCustomStringTypeValidate/json_string
=== RUN   TestAAPCustomStringTypeValidate/yaml_string
=== PAUSE TestAAPCustomStringTypeValidate/yaml_string
=== CONT  TestAAPCustomStringTypeValidate/yaml_string_no_newline
=== CONT  TestAAPCustomStringTypeValidate/json_object
=== CONT  TestAAPCustomStringTypeValidate/null
=== CONT  TestAAPCustomStringTypeValidate/json_string
=== RUN   TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference
=== PAUSE TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference
=== RUN   TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference_with_newline
=== PAUSE TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference_with_newline
=== CONT  TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_values
=== CONT  TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference_with_newline
=== CONT  TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference
=== CONT  TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_whitespace_difference
=== CONT  TestAAPCustomStringTypeValidate/empty-struct
=== CONT  TestAAPCustomStringTypeValidate/wrong-value-type
=== CONT  TestAAPCustomStringTypeValidate/unknown
=== CONT  TestAAPCustomStringTypeValidate/yaml_string
=== CONT  TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_byte-for-byte_match
=== CONT  TestAAPCustomStringStringSemanticEquals/not_equal_-_array_item_order_difference
=== CONT  TestAAPCustomStringStringSemanticEquals/not_equal_-_additional_field
=== CONT  TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_names
--- PASS: TestAAPCustomStringTypeValidate (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/null (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/yaml_string (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/empty-struct (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/unknown (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/json_object (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/wrong-value-type (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/json_string (0.00s)
    --- PASS: TestAAPCustomStringTypeValidate/yaml_string_no_newline (0.00s)
--- PASS: TestAAPCustomStringStringSemanticEquals (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_byte-for-byte_match (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/not_equal_-_array_item_order_difference (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/not_equal_-_additional_field (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_names (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/not_equal_-_mismatched_field_values (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference_with_newline (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/semantically_equal_-_yaml_no_difference (0.00s)
    --- PASS: TestAAPCustomStringStringSemanticEquals/semantically_equal_-_object_whitespace_difference (0.00s)
PASS
ok  	github.com/ansible/terraform-provider-aap/internal/provider/customtypes	0.492s
```

</details>

File: internal/provider/group_resource_test.go [hunk 1]
```diff
@@ -195,7 +195,7 @@ func TestAccGroupResource(t *testing.T) {
 					testAccCheckGroupResourceValues(&groupApiModel, groupName, "", ""),
 					resource.TestCheckResourceAttr("aap_group.test", "name", groupName),
 					resource.TestCheckResourceAttrPair("aap_group.test", "inventory_id", "aap_inventory.test", "id"),
-					resource.TestMatchResourceAttr("aap_group.test", "url", regexp.MustCompile("^/api/v2/groups/[0-9]*/$")),
+					resource.TestMatchResourceAttr("aap_group.test", "url", regexp.MustCompile("^/api(/controller)?/v2/groups/[0-9]*/$")),
```
Comment (PabloHiro) [inline internal/provider/group_resource_test.go:198]: Not asking for this to be changed, but thinking out loud.

I wonder if instead of using regex, and thinking far into the future, we can have this as a `urlPrefix` variable so we don't have to put it all over the code.

File: internal/provider/client.go [hunk 2]
```diff
@@ -18,6 +18,7 @@ type ProviderHTTPClient interface {
 	doRequest(method string, path string, data io.Reader) (*http.Response, []byte, error)
 	Create(path string, data io.Reader) ([]byte, diag.Diagnostics)
 	Get(path string) ([]byte, diag.Diagnostics)
```
Comment (PabloHiro) [inline internal/provider/client.go:20]: Now that we have `GetStatus` instead of `Get`, should this be removed from the interface definition?

File: internal/provider/job_resource.go [hunk 3]
```diff
@@ -175,7 +175,17 @@ func (r *JobResource) Read(ctx context.Context, req resource.ReadRequest, resp *
...
 
 	// Get latest job data from AAP
-	readResponseBody, diags := r.client.Get(data.URL.ValueString())
+	readResponseBody, diags, status := r.client.GetWithStatus(data.URL.ValueString())
+
+	// Check if the response is 404, meaning the job does not exist and should be recreated
+	if status == 404 {
+		resp.Diagnostics.AddWarning(
+			"Job not found",
+			"The job was not found. It may have been deleted. The job will be recreated.",
```
Comment (PabloHiro) [inline internal/provider/job_resource.go:184]: It is possible to detect if the job was present in the state right? Can we only create the warning when the job was present in the state? I think this warning can be confusing for a user running this for the first time.

File: internal/provider/client.go (hunk 2 above)
Comment (PabloHiro) [reply internal/provider/client.go:20]: It does not seem like I can resolve threads in this repo yet, but considered this closed please, thank you both for the explanation :)

File: internal/provider/group_resource_test.go (hunk 1 above)
Comment (dleehr) [reply internal/provider/group_resource_test.go:198]: For sure - There is certainly duplication here that could be refactored, but not something I'm going to take on in **this** PR 😄. And as we understand more about what the purpose of these checks are, we may want to change this in other ways.

Certainly appreciate the observation 👍

File: internal/provider/job_resource.go (hunk 3 above)
Comment (dleehr) [reply internal/provider/job_resource.go:184]: Great question, but we don't actually need to detect that 😺. It's already factored into the design of the provider via the terraform plugin framework. 

This method (`Read`) is only called when an `aap_job` resource **is** present in the state and has a `URL` recorded. See https://developer.hashicorp.com/terraform/plugin/framework/resources/read#define-read-method for similar examples. So we can only get a 404 if we already have a job URL, and that comes from the state.

When the Job does not yet exist, it's not in the state, so terraform calls `Create` instead, which [launches](https://github.com/ansible/terraform-provider-aap/blob/main/internal/provider/job_resource.go#L155) the job and [records it in the state](https://github.com/ansible/terraform-provider-aap/blob/main/internal/provider/job_resource.go#L161). See https://developer.hashicorp.com/terraform/plugin/framework/resources/create.

Comment (dleehr) [reply internal/provider/job_resource.go:184]: With the following `main.tf`:

```hcl
terraform {
  required_providers {
    aap = {
      source = "ansible/aap"
      version = "1.1.2"
    }
  }
}

provider "aap" {
  host = "http://localhost:9080"
  username = "admin"
  password = "..."
}

data "aap_inventory" "my_inventory" {
  id = 1
}

resource "aap_job" "my_job" {
  job_template_id = 7
  inventory_id = data.aap_inventory.my_inventory.id
}

```

The output of `terraform plan` below:

```
$ terraform plan
data.aap_inventory.my_inventory: Reading...
data.aap_inventory.my_inventory: Read complete after 0s [name=Demo Inventory]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aap_job.my_job will be created
  + resource "aap_job" "my_job" {
      + ignored_fields  = (known after apply)
      + inventory_id    = 1
      + job_template_id = 7
      + job_type        = (known after apply)
      + status          = (known after apply)
      + url             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.

Comment (dleehr) [reply internal/provider/job_resource.go:184]: I delete the job in AAP and re-run `terraform plan`. That's when it shows the warning.

```
$ terraform plan
data.aap_inventory.my_inventory: Reading...
data.aap_inventory.my_inventory: Read complete after 0s [name=Demo Inventory]
aap_job.my_job: Refreshing state...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aap_job.my_job will be created
  + resource "aap_job" "my_job" {
      + ignored_fields  = (known after apply)
      + inventory_id    = 1
      + job_template_id = 7
      + job_type        = (known after apply)
      + status          = (known after apply)
      + url             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Job not found
│ 
│   with aap_job.my_job,
│   on main.tf line 20, in resource "aap_job" "my_job":
│   20: resource "aap_job" "my_job" {
│ 
│ The job was not found. It may have been deleted. The job will be recreated.
╵

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

Comment (PabloHiro) [reply internal/provider/job_resource.go:184]: Thank you Dan! The links above are great resources.

**Review by PabloHiro — APPROVED** [review]

**Comment by dleehr** [comment]
> Looks like I need a changelog fragment for this. Edit: and docs!

Done in 3a1f5d25409063c976fe48c4a1a50a28e0e23169.

lint check is failing, see #63
